server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # 어떤 주소로 접속하든 무조건 index.html을 보여주도록 설정
        try_files $uri $uri/ /index.html;
    }
}